name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: bun install && bun install -g @lhci/cli@0.14.x
      - run: bun run build
      - run: lhci autorun
